### ISSUE TITLE
Fail export when requested model isn't found

### ISSUE THREAD

**Issue by chimaerase** [frothga/n2a#125]
While experimenting with model exports, I was initially confused by N2A's behavior of exporting a model, even when the requested one isn't found (or, e.g. its repo isn't marked as visible).  The current behavior seems to be that a model is always exported, even if the requested one doesn't exist.  When the desired one exists, it seems to be exported correctly.

```bash
# Export a non-existent model
$ java -jar n2a.jar -export -model=LifeTheUniverseAndEverything -file=/home/sim_user/n2a/models/42/model.bin

 $n = 1
 $p = $t<1

sim_user@25fd8fd75b5e:/usr/local/sim-rest-api$ ls /home/sim_user/n2a/models/42/
model.bin  model.sh
sim_user@25fd8fd75b5e:/usr/local/sim-rest-api$ cd /home/sim_user/n2a/models/42/
sim_user@25fd8fd75b5e:~/n2a/models/42$ ./model.sh
sim_user@25fd8fd75b5e:~/n2a/models/42$ ls
err  finished  model.bin  model.sh  out
sim_user@25fd8fd75b5e:~/n2a/models/42$ cat finished
success
```

**Comment by frothga** [comment]
Interesting bug! When export is called from the GUI, there is always a valid model selected. The command-line version doesn't bother checking, but that should be easy to add.

**Comment by frothga** [comment]
Added error reporting in Main.java.
